### ISSUE TITLE
Memorable name

### ISSUE THREAD

**Issue by Jawnnypoo** [JayNewstrom/JsonDelight#13]
This looks like an awesome library! Right now though, I could forsee it being somewhat difficult to discuss with colleges. "Have you seen that Android JSON parsing library, json?" Just sounds and seems a little odd. Since it is inspired by SQLDelight, maybe you could call it something like JsonDelight? 

Hope this does not come off as rude, I just think that this library could benefit from a less ambiguous name!

**Comment by JayNewstrom** [comment]
Thanks for the issue! I agree the name is not good. I like the idea of JsonDelight, for the reason you mentioned, but I'm open to other names as well. If you or any others want to suggest other names, I'd love to find the best name for the project.
